INSERT INTO DEPARTAMENTO (NOME, LOCAL) VALUES ('TI', 'RIO DE JANEIRO');
INSERT INTO DEPARTAMENTO (NOME, LOCAL) VALUES ('NEGOCIO', 'SAO PAULO');
INSERT INTO DEPARTAMENTO (NOME, LOCAL) VALUES ('RH', 'CURITIBA');
INSERT INTO DEPARTAMENTO (NOME, LOCAL) VALUES ('FINANCEIRO', 'SANTA CATARINA');

INSERT INTO USUARIO (NOME, SENHA, PAPEL) VALUES ('admin', 'senha123', 'ADMIN');
INSERT INTO USUARIO (NOME, SENHA, PAPEL) VALUES ('user', 'senha123', 'USER');
INSERT INTO USUARIO (NOME, SENHA, PAPEL) VALUES ('chefe', 'senha123', 'CHEFE');

INSERT INTO FUNCIONARIO (NOME, TELEFONE, EMAIL, ENDERECO, DATA_NASCIMENTO, DEPARTAMENTO_ID)
VALUES ('test1', '123456789', 'test@example.com', 'rua test', '1996-11-11', 1);

INSERT INTO FUNCIONARIO (NOME, TELEFONE, EMAIL, ENDERECO, DATA_NASCIMENTO, DEPARTAMENTO_ID)
VALUES ('test2', '234567891', 'test2@example.com', 'avenida test', '2024-10-10', 2);

INSERT INTO FUNCIONARIO_DEPARTAMENTO (FUNCIONARIO_ID, DEPARTAMENTO_ID) VALUES (1, 1);
INSERT INTO FUNCIONARIO_DEPARTAMENTO (FUNCIONARIO_ID, DEPARTAMENTO_ID) VALUES (2, 2);
