CREATE TABLE DEPARTAMENTO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    LOCAL VARCHAR(255)
);

CREATE TABLE USUARIO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    SENHA VARCHAR(40),
    PAPEL VARCHAR(20)
);

CREATE TABLE FUNCIONARIO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(255),
    ENDERECO VARCHAR(255),
    DATA_NASCIMENTO DATE,
    DEPARTAMENTO_ID BIGINT,
    FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTO(ID)
);

CREATE TABLE FUNCIONARIO_DEPARTAMENTO (
    FUNCIONARIO_ID BIGINT,
    DEPARTAMENTO_ID BIGINT,
    PRIMARY KEY (FUNCIONARIO_ID, DEPARTAMENTO_ID),
    FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIO(ID),
    FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTO(ID)
);
